import type { AudioSource } from 'expo-audio';

export const forestStoryAudio: Record<string, AudioSource> = {
  'common-1': require('./audio/common-1.mp3'),
  'common-2': require('./audio/common-2.mp3'),
  'common-3': require('./audio/common-3.mp3'),
  'common-4': require('./audio/common-4.mp3'),
  'common-5': require('./audio/common-5.mp3'),
  'h1-6': require('./audio/h1-6.mp3'),
  'h1-7': require('./audio/h1-7.mp3'),
  'h1-8': require('./audio/h1-8.mp3'),
  'h1-9': require('./audio/h1-9.mp3'),
  'h1-10': require('./audio/h1-10.mp3'),
  'h1-end-a': require('./audio/h1-end-a.mp3'),
  'h1-end-b': require('./audio/h1-end-b.mp3'),
  'h1-end-c': require('./audio/h1-end-c.mp3'),
  'h2-6': require('./audio/h2-6.mp3'),
  'h2-7': require('./audio/h2-7.mp3'),
  'h2-8': require('./audio/h2-8.mp3'),
  'h2-9': require('./audio/h2-9.mp3'),
  'h2-10': require('./audio/h2-10.mp3'),
  'h2-end-a': require('./audio/h2-end-a.mp3'),
  'h2-end-b': require('./audio/h2-end-b.mp3'),
  'h2-end-c': require('./audio/h2-end-c.mp3'),
  'h3-6': require('./audio/h3-6.mp3'),
  'h3-7': require('./audio/h3-7.mp3'),
  'h3-8': require('./audio/h3-8.mp3'),
  'h3-9': require('./audio/h3-9.mp3'),
  'h3-10': require('./audio/h3-10.mp3'),
  'h3-end-a': require('./audio/h3-end-a.mp3'),
  'h3-end-b': require('./audio/h3-end-b.mp3'),
  'h3-end-c': require('./audio/h3-end-c.mp3'),
};
