import type { StoryImageMap } from '@/types/story';

export const forestStoryImages: StoryImageMap = {
  'cover.png': require('./assets/cover.jpg'),
  'common-1.png': require('./assets/start.jpg'),
  'common-2.png': require('./assets/common/p01-a.jpg'),
  'common-3.png': require('./assets/common/p02-a.jpg'),
  'common-4.png': require('./assets/common/p03-a.jpg'),
  'common-5.png': require('./assets/common/p04-a.jpg'),

  'common-p2-a.png': require('./assets/common/p01-a.jpg'),
  'common-p2-b.png': require('./assets/common/p01-b.jpg'),
  'common-p2-c.png': require('./assets/common/p01-c.jpg'),
  'common-p3-a.png': require('./assets/common/p02-a.jpg'),
  'common-p3-b.png': require('./assets/common/p02-b.jpg'),
  'common-p3-c.png': require('./assets/common/p02-c.jpg'),
  'common-p4-a.png': require('./assets/common/p03-a.jpg'),
  'common-p4-b.png': require('./assets/common/p03-b.jpg'),
  'common-p4-c.png': require('./assets/common/p03-c.jpg'),
  'common-p5-a.png': require('./assets/common/p04-a.jpg'),
  'common-p5-b.png': require('./assets/common/p04-b.jpg'),
  'common-p5-c.png': require('./assets/common/p04-c.jpg'),

  'h1-p6.png': require('./assets/common/p05-a.jpg'),
  'h2-p6.png': require('./assets/common/p05-b.jpg'),
  'h3-p6.png': require('./assets/common/p05-c.jpg'),

  'h1-6.png': require('./assets/common/p05-a.jpg'),
  'h1-7.png': require('./assets/story1-yaraliadam/p06-a.jpg'),
  'h1-8.png': require('./assets/story1-yaraliadam/p07-a.jpg'),
  'h1-9.png': require('./assets/story1-yaraliadam/p08-a.jpg'),
  'h1-10.png': require('./assets/story1-yaraliadam/p09-a.jpg'),
  'h1-p7-a.png': require('./assets/story1-yaraliadam/p06-a.jpg'),
  'h1-p7-b.png': require('./assets/story1-yaraliadam/p06-b.jpg'),
  'h1-p7-c.png': require('./assets/story1-yaraliadam/p06-c.jpg'),
  'h1-p8-a.png': require('./assets/story1-yaraliadam/p07-a.jpg'),
  'h1-p8-b.png': require('./assets/story1-yaraliadam/p07-b.jpg'),
  'h1-p8-c.png': require('./assets/story1-yaraliadam/p07-c.jpg'),
  'h1-p9-a.png': require('./assets/story1-yaraliadam/p08-a.jpg'),
  'h1-p9-b.png': require('./assets/story1-yaraliadam/p08-b.jpg'),
  'h1-p9-c.png': require('./assets/story1-yaraliadam/p08-c.jpg'),
  'h1-p10-a.png': require('./assets/story1-yaraliadam/p09-a.jpg'),
  'h1-p10-b.png': require('./assets/story1-yaraliadam/p09-b.jpg'),
  'h1-p10-c.png': require('./assets/story1-yaraliadam/p09-c.jpg'),
  'h1-end-a.png': require('./assets/story1-yaraliadam/ending-a.jpg'),
  'h1-end-b.png': require('./assets/story1-yaraliadam/ending-b.jpg'),
  'h1-end-c.png': require('./assets/story1-yaraliadam/ending-c.jpg'),

  'h2-6.png': require('./assets/common/p05-b.jpg'),
  'h2-7.png': require('./assets/story2-gizlikapi/p06-a.jpg'),
  'h2-8.png': require('./assets/story2-gizlikapi/p07-a.jpg'),
  'h2-9.png': require('./assets/story2-gizlikapi/p08-a.jpg'),
  'h2-10.png': require('./assets/story2-gizlikapi/p09-a.jpg'),
  'h2-p7-a.png': require('./assets/story2-gizlikapi/p06-a.jpg'),
  'h2-p7-b.png': require('./assets/story2-gizlikapi/p06b.jpg'),
  'h2-p7-c.png': require('./assets/story2-gizlikapi/p06-c.jpg'),
  'h2-p8-a.png': require('./assets/story2-gizlikapi/p07-a.jpg'),
  'h2-p8-b.png': require('./assets/story2-gizlikapi/p07-b.jpg'),
  'h2-p8-c.png': require('./assets/story2-gizlikapi/p07-c.jpg'),
  'h2-p9-a.png': require('./assets/story2-gizlikapi/p08-a.jpg'),
  'h2-p9-b.png': require('./assets/story2-gizlikapi/p08-b.jpg'),
  'h2-p9-c.png': require('./assets/story2-gizlikapi/p08-c.jpg'),
  'h2-p10-a.png': require('./assets/story2-gizlikapi/p09-a.jpg'),
  'h2-p10-b.png': require('./assets/story2-gizlikapi/p09-b.jpg'),
  'h2-p10-c.png': require('./assets/story2-gizlikapi/p09-c.jpg'),
  'h2-end-a.png': require('./assets/story2-gizlikapi/ending-a.jpg'),
  'h2-end-b.png': require('./assets/story2-gizlikapi/ending-b.jpg'),
  'h2-end-c.png': require('./assets/story2-gizlikapi/ending-c.jpg'),

  'h3-6.png': require('./assets/common/p05-c.jpg'),
  'h3-7.png': require('./assets/story3-tas/p06-a.jpg'),
  'h3-8.png': require('./assets/story3-tas/p07-a.jpg'),
  'h3-9.png': require('./assets/story3-tas/p08-a.jpg'),
  'h3-10.png': require('./assets/story3-tas/p09-a.jpg'),
  'h3-p7-a.png': require('./assets/story3-tas/p06-a.jpg'),
  'h3-p7-b.png': require('./assets/story3-tas/p06-b.jpg'),
  'h3-p7-c.png': require('./assets/story3-tas/p06-c.jpg'),
  'h3-p8-a.png': require('./assets/story3-tas/p07-a.jpg'),
  'h3-p8-b.png': require('./assets/story3-tas/p07-b.jpg'),
  'h3-p8-c.png': require('./assets/story3-tas/p07-c.jpg'),
  'h3-p9-a.png': require('./assets/story3-tas/p08-a.jpg'),
  'h3-p9-b.png': require('./assets/story3-tas/p08-b.jpg'),
  'h3-p9-c.png': require('./assets/story3-tas/p08-c.jpg'),
  'h3-p10-a.png': require('./assets/story3-tas/p09-a.jpg'),
  'h3-p10-b.png': require('./assets/story3-tas/p09-b.jpg'),
  'h3-p10-c.png': require('./assets/story3-tas/p09-c.jpg'),
  'h3-end-a.png': require('./assets/story3-tas/ending-a.jpg'),
  'h3-end-b.png': require('./assets/story3-tas/ending-b.jpg'),
  'h3-end-c.png': require('./assets/story3-tas/ending-c.jpg'),
};
