import type { StoryImageMap } from '@/types/story';

export const akilliTavsanMomoImages: StoryImageMap = {
  'cover.png': require('./assets/giriş paragrafı.png'),
  'start.png': require('./assets/giriş paragrafı.png'),
  'p1-a.png': require('./assets/paragraf1_A.png'),
  'p1-b.png': require('./assets/paragraf1_B.png'),
  'p1-c.png': require('./assets/paragraf1_C.png'),
  'p2-a.png': require('./assets/paragraf2_A.png'),
  'p2-b.png': require('./assets/paragraf2_B.png'),
  'p2-c.png': require('./assets/paragraf2_C.png'),
  'p3-a.png': require('./assets/paragraf3_A.png'),
  'p3-b.png': require('./assets/paragraf3_B.png'),
  'p3-c.png': require('./assets/paragraf3_C.png'),
  'p4-a.png': require('./assets/paragraf4_A.png'),
  'p4-b.png': require('./assets/paragraf4_B.png'),
  'p4-c.png': require('./assets/paragraf4_C.png'),
  'p5-a.png': require('./assets/paragraf5_A (2).png'),
  'p5-b.png': require('./assets/paragraf5_B.png'),
  'p5-c.png': require('./assets/paragraf5_C.png'),
  'h1-p6-a.png': require('./assets/H1_paragraf6_A.png'),
  'h1-p6-b.png': require('./assets/H1_paragraf6_B.png'),
  'h1-p6-c.png': require('./assets/H1_paragraf6_C.png'),
  'h1-p7-a.png': require('./assets/H1_paragraf7_A.png'),
  'h1-p7-b.png': require('./assets/H1_paragraf7_B.png'),
  'h1-p7-c.png': require('./assets/H1_paragraf7_C.png'),
  'h1-p8-a.png': require('./assets/H1_paragraf8_A.png'),
  'h1-p8-b.png': require('./assets/H1_paragraf8_B.png'),
  'h1-p8-c.png': require('./assets/H1_paragraf8_C.png'),
  'h1-p9-a.png': require('./assets/H1_paragraf9_A.png'),
  'h1-p9-b.png': require('./assets/H1_paragraf9_B..png'),
  'h1-p9-c.png': require('./assets/H1_paragraf9_C.png'),
  'h1-p10-a.png': require('./assets/H1_paragraf10_A.png'),
  'h1-p10-b.png': require('./assets/H1_paragraf10_B.png'),
  'h1-p10-c.png': require('./assets/H1_paragraf10_C.png'),
  'h1-end.png': require('./assets/H1_11.png'),
  'h2-p6-a.png': require('./assets/H2_paragraf6_A.png'),
  'h2-p6-b.png': require('./assets/H2_paragraf6_B.png'),
  'h2-p6-c.png': require('./assets/H2_paragraf6_C.png'),
  'h2-p7-a.png': require('./assets/H2_paragraf7_A.png'),
  'h2-p7-b.png': require('./assets/H2_paragraf7_B.png'),
  'h2-p7-c.png': require('./assets/H2_paragraf7_C.png'),
  'h2-p8-a.png': require('./assets/H2_paragraf8_A.png'),
  'h2-p8-b.png': require('./assets/H2_paragraf8_B.png'),
  'h2-p8-c.png': require('./assets/H2_paragraf8_C.png'),
  'h2-p9-a.png': require('./assets/H2_paragraf9_A.png'),
  'h2-p9-b.png': require('./assets/H2_paragraf9_B.png'),
  'h2-p9-c.png': require('./assets/H2_paragraf9_C.png'),
  'h2-p10-a.png': require('./assets/H2_paragraf10_A.png'),
  'h2-p10-b.png': require('./assets/H2_paragraf10_B.png'),
  'h2-p10-c.png': require('./assets/H2_paragraf10_C.png'),
  'h2-end.png': require('./assets/H2_11.png'),
  'h3-p6-a.png': require('./assets/H3_paragraf6_A.png'),
  'h3-p6-b.png': require('./assets/H3_paragraf6_B.png'),
  'h3-p6-c.png': require('./assets/H3_paragraf6_C.png'),
  'h3-p7-a.png': require('./assets/H3_paragraf7_A.png'),
  'h3-p7-b.png': require('./assets/H3_paragraf7_B.png'),
  'h3-p7-c.png': require('./assets/H3_paragraf7_C.png'),
  'h3-p8-a.png': require('./assets/H3_paragraf8_A.png'),
  'h3-p8-b.png': require('./assets/H3_paragraf8_B.png'),
  'h3-p8-c.png': require('./assets/H3_paragraf8_C.png'),
  'h3-p9-a.png': require('./assets/H3_paragraf9_A.png'),
  'h3-p9-b.png': require('./assets/H3_paragraf9_B.png'),
  'h3-p9-c.png': require('./assets/H3_paragraf9_C.png'),
  'h3-p10-a.png': require('./assets/H3_paragraf10_A.png'),
  'h3-p10-b.png': require('./assets/H3_paragraf10_B.png'),
  'h3-p10-c.png': require('./assets/H3_paragraf10_C.png'),
  'h3-end.png': require('./assets/H3_11.png'),
};
