import type { AudioSource } from 'expo-audio';

export const dehlizinGizemiAudio: Record<string, AudioSource> = {
  'ortak-1': require('./audio/ortak-1.mp3'),
  'ortak-2': require('./audio/ortak-2.mp3'),
  'ortak-3': require('./audio/ortak-3.mp3'),
  'ortak-4': require('./audio/ortak-4.mp3'),
  'ortak-5': require('./audio/ortak-5.mp3'),
  'sandik-6': require('./audio/sandik-6.mp3'),
  'sandik-7': require('./audio/sandik-7.mp3'),
  'sandik-8': require('./audio/sandik-8.mp3'),
  'sandik-9': require('./audio/sandik-9.mp3'),
  'sandik-10': require('./audio/sandik-10.mp3'),
  'sandik-son-1': require('./audio/sandik-son-1.mp3'),
  'sandik-son-2': require('./audio/sandik-son-2.mp3'),
  'sandik-son-3': require('./audio/sandik-son-3.mp3'),
  'gecit-6': require('./audio/gecit-6.mp3'),
  'gecit-7': require('./audio/gecit-7.mp3'),
  'gecit-8': require('./audio/gecit-8.mp3'),
  'gecit-9': require('./audio/gecit-9.mp3'),
  'gecit-10': require('./audio/gecit-10.mp3'),
  'gecit-son-1': require('./audio/gecit-son-1.mp3'),
  'gecit-son-2': require('./audio/gecit-son-2.mp3'),
  'gecit-son-3': require('./audio/gecit-son-3.mp3'),
  'emanet-6': require('./audio/emanet-6.mp3'),
  'emanet-7': require('./audio/emanet-7.mp3'),
  'emanet-8': require('./audio/emanet-8.mp3'),
  'emanet-9': require('./audio/emanet-9.mp3'),
  'emanet-10': require('./audio/emanet-10.mp3'),
  'emanet-son-1': require('./audio/emanet-son-1.mp3'),
  'emanet-son-2': require('./audio/emanet-son-2.mp3'),
  'emanet-son-3': require('./audio/emanet-son-3.mp3'),
};
